<a href="https://colab.research.google.com/github/kniJanjaras/229352-StatisticalLearning/blob/main/Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [60]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [61]:
a = torch.tensor(8)
b = torch.tensor(9)
print(a)
print(b)
print(a+b)

tensor(8)
tensor(9)
tensor(17)


### Convert a tensor to scalar

In [62]:
a.item()

8

### Creating 2D tensor

In [63]:
A = torch.tensor([[1, 2], [3, 4]])
print(A)

tensor([[1, 2],
        [3, 4]])


## Tensor and Numpy

### Convert from tensor to numpy array

In [64]:
A.numpy()

array([[1, 2],
       [3, 4]])

### Convert from numpy array to tensor

In [65]:
B = np.array([[1, 2], [3, 4]])

C = torch.from_numpy(B)
print(C)

tensor([[1, 2],
        [3, 4]])


## Basic operations

In [66]:
D = 2*C

E = C - 10

print(D)
print(E)

tensor([[2, 4],
        [6, 8]])
tensor([[-9, -8],
        [-7, -6]])


### Matrix multiplication

In [67]:
print(torch.matmul(D, E))
print(torch.mm(D, E))
print(D @ E)

tensor([[ -46,  -40],
        [-110,  -96]])
tensor([[ -46,  -40],
        [-110,  -96]])
tensor([[ -46,  -40],
        [-110,  -96]])


### Matrix transpose

In [68]:
print(C)
print( C.t() )

tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])


## Creating a specific type of tensor

In [69]:
# print(torch.zeros(2,3))
# print(torch.ones(2,3))
# print(torch.rand(2,3))
# print(torch.randn(2,3))  # sample each number from N(0, 1)
# print(torch.arange(9))

In [70]:
print(torch.ones(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [71]:
print(torch.zeros(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [72]:
print(torch.rand(2,3))

tensor([[0.4901, 0.5210, 0.5850],
        [0.8046, 0.2228, 0.6400]])


In [73]:
print(torch.randn(2,3))

tensor([[-1.0309, -0.6497,  0.1146],
        [-0.2398,  0.5303, -0.7381]])


In [74]:
print(torch.arange(9))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


## Tensor's shape

### Checking the shape of a tensor

In [75]:
F = torch.zeros((4, 5))
print(F.shape)
print(F.size())

torch.Size([4, 5])
torch.Size([4, 5])


### Changing the shape of a tensor

In [76]:
G = torch.arange(6)
print(G.view(2, 3))
print(G.reshape(2, 3))

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [77]:
H = torch.arange(6)
I = torch.stack([H, H, H, H], axis=0)
J = torch.stack([H, H, H, H], axis=1)
print(I)
print(J)

tensor([[0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5]])
tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5]])


In [78]:
# concatenate

I = torch.cat([H, H, H, H], axis=0)
print(I)
# J = torch.cat([H, H, H, H], axis=1)
#print(J)

tensor([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])


### Squeezing a tensor (removing an extra dimension)

In [79]:
# [[1,2]] this is (1,2) tensor, want (2,)
print("H=", H) # shape = (6,)
K = H.reshape(1,6)
print("K=", K)
print(K.shape)

H= tensor([0, 1, 2, 3, 4, 5])
K= tensor([[0, 1, 2, 3, 4, 5]])
torch.Size([1, 6])


In [80]:
print(K.squeeze())

tensor([0, 1, 2, 3, 4, 5])


In [81]:
# H.shape = (6, )
L = H.unsqueeze(axis=0)  # L.shape(1, 6)
M = H.unsqueeze(axis=1)  # L.shape(6, 1)
print(L)
print(M)

tensor([[0, 1, 2, 3, 4, 5]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])


## Indexing

In [82]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


## PyTorch and GPU

check if GPU is available

In [83]:
torch.cuda.is_available()

True

In [84]:
Q = torch.tensor([1, 2, 3])
print(Q.device)

cpu


In [85]:
R = Q.to('cuda')
print(Q.device)
print(R.device)

cpu
cuda:0


In [86]:
R.cpu().numpy()

array([1, 2, 3])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [87]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [88]:
#1. random N(0,1) ใช้ torch.rand
X = torch.rand(200,7)
b = torch.rand(8,1)
e = torch.rand(200,1)

In [89]:
print(X.size())
print(b.size())
print(e.size())

torch.Size([200, 7])
torch.Size([8, 1])
torch.Size([200, 1])


In [90]:
#2. create
one = torch.ones(200,1)
print(one.shape)

torch.Size([200, 1])


In [91]:
#3. modify tensor X
X = torch.cat([one, X], dim =1)

print(X.shape)

torch.Size([200, 8])


In [92]:
#4. comput y "y = Xb +e"
y = X @ b + e
print(y)

tensor([[2.1867],
        [1.3453],
        [1.7612],
        [2.9144],
        [2.7352],
        [1.9293],
        [2.3765],
        [2.2230],
        [3.2829],
        [2.4675],
        [3.1561],
        [2.0380],
        [2.3275],
        [2.7140],
        [1.9877],
        [2.6294],
        [2.1284],
        [2.6556],
        [2.3952],
        [1.9665],
        [2.2826],
        [1.1899],
        [2.3482],
        [2.0304],
        [2.9763],
        [3.4965],
        [2.2701],
        [2.5759],
        [2.2759],
        [2.0102],
        [2.5669],
        [3.0004],
        [1.3919],
        [2.3565],
        [2.2911],
        [1.7002],
        [1.9913],
        [2.0004],
        [2.9456],
        [2.0820],
        [2.0098],
        [2.3056],
        [1.3049],
        [1.9178],
        [1.8992],
        [2.5282],
        [1.8523],
        [2.6676],
        [2.6502],
        [2.4109],
        [2.6863],
        [2.2696],
        [2.0760],
        [1.1242],
        [2.7097],
        [1

In [98]:
#5. หาb_hat
b_hat = torch.inverse(X.T @ X) @( X.T @ y)
print(b_hat)

tensor([[0.5845],
        [0.0772],
        [0.3978],
        [1.0105],
        [0.8417],
        [0.0456],
        [0.6789],
        [0.2275]])


In [99]:
#6. หาy_hat
y_hat = X @ b_hat
print(y_hat)

tensor([[2.5858],
        [1.4344],
        [2.1063],
        [3.0317],
        [2.4133],
        [1.8238],
        [2.0706],
        [2.1391],
        [3.0320],
        [2.0846],
        [2.8915],
        [2.0585],
        [2.1506],
        [2.2953],
        [1.7762],
        [2.7414],
        [2.4286],
        [2.6088],
        [2.5063],
        [2.5226],
        [2.0910],
        [1.4621],
        [2.3262],
        [2.3112],
        [2.5471],
        [3.0925],
        [2.4444],
        [2.2661],
        [2.1219],
        [2.2375],
        [2.7724],
        [2.7628],
        [1.5035],
        [2.5703],
        [2.2485],
        [2.1156],
        [2.1829],
        [2.1233],
        [2.7429],
        [2.2504],
        [2.4497],
        [2.0142],
        [1.7499],
        [2.3138],
        [2.3106],
        [2.3336],
        [2.0259],
        [2.6502],
        [2.2820],
        [2.1376],
        [2.3534],
        [2.0414],
        [2.0567],
        [1.2803],
        [2.7973],
        [1

In [100]:
#7. Convert both y and y_hat from tensor to Numpy array and calculate MSE
y_np = y.numpy()
y_hat_np = y_hat.detach().numpy()

MSE = np.mean((y_np - y_hat_np) ** 2)
print("MSE:", MSE)

MSE: 0.07890932
